# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres_post:
    container_name: postgres_post_container
    build: postgres
    env_file:
      - .env
    volumes:
      - postgres_post:${PGDATA:-/data/postgres}
    ports:
      - 5432:5432
    networks:
      - postgres_post
    restart: unless-stopped

  pgadmin_post:
    container_name: pgadmin_post_container
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    volumes:
      - pgadmin_post:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres_post
    restart: unless-stopped

networks:
  postgres_post:
    driver: bridge

volumes:
  postgres_post:
  pgadmin_post:
